// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUoBCfsMsmbUVCtAtats_yiagg2ZvbHyQ',
    appId: '1:214941779513:web:e9415ee0b390dc4ab2efe8',
    messagingSenderId: '214941779513',
    projectId: 'hospital-manager-uni',
    authDomain: 'hospital-manager-uni.firebaseapp.com',
    storageBucket: 'hospital-manager-uni.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJdQAkNoDxQ-l8FBooj859RFEguE_rVos',
    appId: '1:214941779513:android:d58c30fae9d4f523b2efe8',
    messagingSenderId: '214941779513',
    projectId: 'hospital-manager-uni',
    storageBucket: 'hospital-manager-uni.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD04GVRTzdjbWiHsCwLKA1TduAAGm7tOjY',
    appId: '1:214941779513:ios:876e78b66660bac4b2efe8',
    messagingSenderId: '214941779513',
    projectId: 'hospital-manager-uni',
    storageBucket: 'hospital-manager-uni.firebasestorage.app',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD04GVRTzdjbWiHsCwLKA1TduAAGm7tOjY',
    appId: '1:214941779513:ios:876e78b66660bac4b2efe8',
    messagingSenderId: '214941779513',
    projectId: 'hospital-manager-uni',
    storageBucket: 'hospital-manager-uni.firebasestorage.app',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUoBCfsMsmbUVCtAtats_yiagg2ZvbHyQ',
    appId: '1:214941779513:web:dd18f016c7514087b2efe8',
    messagingSenderId: '214941779513',
    projectId: 'hospital-manager-uni',
    authDomain: 'hospital-manager-uni.firebaseapp.com',
    storageBucket: 'hospital-manager-uni.firebasestorage.app',
  );
}
